#pragma once


#define VITA_SCREEN_W 960
#define VITA_SCREEN_H 544

enum ui_key_code {
    UI_KEY_CODE_VITA_DPAD_LEFT = 1,
    UI_KEY_CODE_VITA_DPAD_RIGHT = 1 << 1,
    UI_KEY_CODE_VITA_DPAD_UP = 1 << 2,
    UI_KEY_CODE_VITA_DPAD_DOWN = 1 << 3,
    UI_KEY_CODE_VITA_ACTION_SQUARE = 1 << 4,
    UI_KEY_CODE_VITA_ACTION_CIRCLE = 1 << 5,
    UI_KEY_CODE_VITA_ACTION_TRIANGLE = 1 << 6,
    UI_KEY_CODE_VITA_ACTION_CROSS = 1 << 7,
    UI_KEY_CODE_VITA_TRIGGER_L = 1 << 8,
    UI_KEY_CODE_VITA_TRIGGER_R = 1 << 9,
    UI_KEY_CODE_VITA_START = 1 << 10,
    UI_KEY_CODE_VITA_SELECT = 1 << 11,
    UI_KEY_CODE_VITA_VIRTUAL_OK = 1 << 12,
    UI_KEY_CODE_VITA_VIRTUAL_CANCEL = 1 << 13,
};

enum ui_key_state {
    UI_KEY_STATE_DOWN,
    UI_KEY_STATE_UP,
};
